### ISSUE TITLE
!Important - original html files contain too many broken links

### ISSUE THREAD

**Issue by zhjch05** [4cw/4cw#13]
The links in those html files contain many broken links - both external and internal. Anyone has ideas how to do with those links?

**Comment by tjhickey724** [comment]
Don’t worry about the broken links — we’ll work with Dr. Blumenthal to get the right links…
For now, lets just mark the links e.g. use the URL http://brokenlink.edu <http://brokenlink.edu/>

Best,
—Tim—

**Comment by zhjch05** [comment]
Thanks! I am closing this issue.
